services:
  - type: web
    name: rag-bot-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GEMINI_API_KEY_PRIMARY
        sync: false
      - key: GEMINI_API_KEY_FALLBACK
        sync: false